@startuml
!include <C4/C4_Context>

title Диаграмма контекста системы (C4 Level 1) для банка "Стандарт" (TO-BE MVP)

Person(client, "Клиент", "Физическое лицо, использующее продукты банка")
Person(back_office, "Сотрудник бэк-офиса", "Обрабатывает заявки, управляет ставками")
Person(call_center, "Оператор кол-центра", "Консультирует клиентов по ставкам")

System(bank_system, "IT-система банка 'Стандарт'", "Комплекс систем для обслуживания розничных клиентов")

System_Ext(telecom, "Телеком-оператор", "Поставщик услуг СМС-информирования")
System_Ext(partner_cc, "Партнёрский кол-центр", "Получает ставки по депозитам")

Rel(client, bank_system, "Подает заявки на депозит, получает уведомления")
Rel(back_office, bank_system, "Работает с онлайн-заявками и ставками")
Rel(call_center, bank_system, "Получает актуальные ставки для консультаций")

Rel(bank_system, telecom, "Отправляет СМС-уведомления")
Rel(bank_system, partner_cc, "Выгружает файл со ставками")

@enduml